from telegram.error import NetworkError


def networkerror(update, context, exception: NetworkError):
    pass
