from telegram.error import TelegramError


def telegramerror(update, context, exception: TelegramError):
    pass
